/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconFa6SolidTrash: typeof import('~icons/fa6-solid/trash')['default']
    PoAgreement: typeof import('./resources/js/components/common/PoAgreement.vue')['default']
    PoAvatar: typeof import('./resources/js/components/common/PoAvatar.vue')['default']
    PoAvatarAward: typeof import('./resources/js/components/common/PoAvatarAward.vue')['default']
    PoBadge: typeof import('./resources/js/components/common/PoBadge.vue')['default']
    PoBlocker: typeof import('./resources/js/components/common/PoBlocker.vue')['default']
    PoBottomNav: typeof import('./resources/js/components/common/PoBottomNav.vue')['default']
    PoButton: typeof import('./resources/js/components/common/PoButton.vue')['default']
    PoChip: typeof import('./resources/js/components/common/PoChip.vue')['default']
    PoComplainer: typeof import('./resources/js/components/common/PoComplainer.vue')['default']
    PoFooter: typeof import('./resources/js/components/common/PoFooter.vue')['default']
    PoHead: typeof import('./resources/js/components/common/PoHead.vue')['default']
    PoInfiniteScroll: typeof import('./resources/js/components/common/PoInfiniteScroll.vue')['default']
    PoInlineLogin: typeof import('./resources/js/components/common/PoInlineLogin.vue')['default']
    PoKarmaInspire: typeof import('./resources/js/components/common/PoKarmaInspire.vue')['default']
    PoLink: typeof import('./resources/js/components/common/PoLink.vue')['default']
    PoListItem: typeof import('./resources/js/components/common/PoListItem.vue')['default']
    PoLoading: typeof import('./resources/js/components/common/PoLoading.vue')['default']
    PoLoginModal: typeof import('./resources/js/components/common/PoLoginModal.vue')['default']
    PoMenuMobileSite: typeof import('./resources/js/components/common/PoMenuMobileSite.vue')['default']
    PoMenuMobileUser: typeof import('./resources/js/components/common/PoMenuMobileUser.vue')['default']
    PoModalClose: typeof import('./resources/js/components/common/PoModalClose.vue')['default']
    PoMsgBlock: typeof import('./resources/js/components/common/PoMsgBlock.vue')['default']
    PoPwaPrompt: typeof import('./resources/js/components/common/PoPwaPrompt.vue')['default']
    PoSharer: typeof import('./resources/js/components/common/PoSharer.vue')['default']
    PoSnackBar: typeof import('./resources/js/components/common/PoSnackBar.vue')['default']
    PoTab: typeof import('./resources/js/components/common/PoTab.vue')['default']
    PoWrapper: typeof import('./resources/js/components/common/PoWrapper.vue')['default']
  }
}
